css: 
  extension: .css
  output: css
css-variables: 
  extension: .css
  output: css-variables
js-variables: 
  extension: .js
  output: js-variables
less:
  extension: .less
  output: less
sass: 
  extension: .sass
  output: sass
scss: 
  extension: .scss
  output: scss
stylus: 
  extension: .styl
  output: stylus
